### ISSUE TITLE
Python plotting scripts broken on Cheyenne

### ISSUE THREAD

**Issue by grantfirl** [NCAR/gmtb-scm#130]
The python environment on Cheyenne has changed and the machine setup scripts need to be updated to use it. [See https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/software/python]

It would be best just to eliminate the need for f90nml to not require users to install it.

However, since plotting will be redone in the near future, it may not be necessary to fix.

**Comment by climbfuji** [comment]
Needs to be fixed for the release.

**Comment by grantfirl** [comment]
Fixed in #162
